name: pip packaging osx

on:
  release:
    types: [published]

env:
  MACOSX_DEPLOYMENT_TARGET: 14.0
  _PYTHON_HOST_PLATFORM: macosx-14.0-universal2
  ARCHFLAGS: "-arch arm64 -arch x86_64"

jobs:
  # Build with minimal supported version of NumPy 1.X with ABI compatibility feature
  wheels:
    # Python 3.11+ is only available for MacOS free version cf. https://github.com/actions/runner-images
    runs-on: macos-14
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - python-version: "3.11"
            numpy-version: "1.23.2"
          - python-version: "3.12"
            numpy-version: "1.26.0"
          - python-version: "3.13"
            numpy-version: "2.1.0"
          - python-version: "3.14"
            numpy-version: "2.3.4"
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      # For python>=3.11, numpy>=2.0 for package build and ABI compatibility with numpy 1.X and 2.X
      # cf. https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice
      - name: Install dependencies
        run: |
          brew --version
          brew install boost eigen gmp mpfr cgal || echo "brew install failed, continuing..."
          ./scripts/build_osx_universal_gmpfr.sh
          # Now the universal libraries are in $PWD/deps-uni/lib
